version: '2'

services:
    djangoapp:
        build: .
        volumes:
            - .:/opt/services/djangoapp/src
            - static_volume:/opt/services/djangoapp/static
            - media_volume:/opt/services/djangoapp/media
        networks:
            - nginx_network
    nginx:
        image: nginx:1.13
        ports:
             - 80:80 # Production
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - static_volume:/opt/services/djangoapp/static
            - media_volume:/opt/services/djangoapp/media
        depends_on:
            - djangoapp
        networks:
            - nginx_network
networks:
    nginx_network:
        driver: bridge

volumes:
    static_volume:
    media_volume:
